### ISSUE TITLE
Move README info to the doc?

### ISSUE THREAD

**Issue by tmigot** [abelsiqueira/JSOSolverTemplates.jl#2]
It feels more in the spirit of the package to have a generic README that would a JSO-compliant solver typically have, and move all the extra information to the documentation of this package.

**Comment by abelsiqueira** [comment]
I agree with moving, but I think a more prominent place. Maybe SolverCore? Maybe the website? Both?

**Comment by tmigot** [comment]
SolverCore would be good, but I feel it is less visited than the website, and also it is probably good to have everything on the website anyway.

**Comment by abelsiqueira** [comment]
I agree to have in the website and some other place. I think SolverCore because it probably only affects people that have to use SolverCore anyway because they're developing solvers.
